name: 'Check YAML files'
description: 'Check for validity YAML files and provide per-line errors'
branding:
  icon: 'briefcase'
  color: 'yellow'
inputs:
  files:
    description: 'Which files need to be checked'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Check YAML files
      env:
        FILES: ${{ inputs.files}}
      run: ${GITHUB_ACTION_PATH}/action.pl $FILES
      shell: bash
