name: Local checks
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - id: foo
      uses: ./
      with:
        files:
          - action.yml
          - .github/workflows/test.yml
